### PR TITLE
Game embedded process

### PR DESCRIPTION
**Pull request by Hilderin**
- Implemented the first version of game embedding for Windows and Linux (when "prefer Wayland" is disabled) for PR https://github.com/godotengine/godot/pull/97257

### New Options in the Game Editor Toolbar:
- **Embed On/Off**: Activates or deactivates embedding. This feature works while the game is running, though it currently closes and restarts the game. Managing the game's display options correctly (e.g., fullscreen, window decorations, etc.) while keeping it running was very complex.
  
- **Auto Focus On/Off**: When enabled, the Game Editor automatically gains focus when the game starts. This was added to save the hassle of manually clicking the Game button each time.
  
- **Keep Aspect Ratio**: Maintains the aspect ratio of the game's window size in the Game Editor when embedding is enabled.

### Additional Features:
- Added the method `Engine.is_embedded()` in GDScript/C#, which is useful for preventing errors when attempting to change unsupported window settings while embedded or for modifying behavior when embedding is active.

### Known Issues:
- There are currently no default keyboard shortcuts to exit mouse capture mode when embedded. This can be inconvenient when using the Game Editor for games like the TPS Demo, which hides the mouse cursor during gameplay.
  - As a workaround, I modified the game to show the mouse on pressing the Escape key instead of returning to the menu in `level.gd`:
```gdscript
func _input(event):
	if event.is_action_pressed("quit"):
		if Engine.is_embedded():
			if Input.get_mouse_mode() == Input.MOUSE_MODE_VISIBLE:
				Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
			else:
				Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
			
		else:
			emit_signal("quit")
```

- In the TPS Demo, errors are printed when starting the game because it's trying to activate fullscreen mode. This happens because when the game is embedded, the `DisplayServer` does not allow changes to the window mode.
  - I fixed this with a simple check:
  
```gdscript
  if !Engine.is_embedded():
      get_window().mode = Settings.config_file.get_value("video", "display_mode")
```

- The scene preview in the scene tabs (mouse over) is shown under the embedded window. This happens because the embedding process is drawn over the editor window, and the previews are simple controls and not popup windows like tooltips. This should be relatively easy to fix using popup windows for previews (like tooltips). There are probably other controls like this that are displayed behind the game window.

### CODE REVIEW

**Comment by arkology** [comment]
https://github.com/user-attachments/assets/44f55ed9-74eb-4500-b6aa-4f643f442a75



Such windows placement is intended, right?

--- 

Also there is noticeable delay of embedded window resizing when resizing editor window:


https://github.com/user-attachments/assets/6a8f8ec1-bfde-4939-bcd2-3c85da0395f0

**Comment by Hilderin** [comment]
Thanks @arkology for tested, very appreciated.

> Such windows placement is intended, right?

No it's not intended, the problem is that the game process is not 100% considered a child by Windows to prevent lags. That means that "modal" popups from the editor does not "lock" the game window. I'll see if I can do something about that.

> Also there is noticeable delay of embedded window resizing when resizing editor window

That's a unfortunate side-effect of the fact that the editor and the game are 2 distinct process. The editor needs to talk the to game process to tell it it's new position and size and the process repaint itself and that is not synchronised. I'm not sure we can do better then that with this technique. I don't think it's a show breaker, I personally don't resize my game editor that much. What do you think?

**Comment by arkology** [comment]
@Hilderin thanks for answers! 
Actually I'm ok with both "issues" I showed in videos, just wanted to share :)

**Comment by arkology** [comment]
Intel GPU is cursed? 
`Godot v4.4.dev (fa8af1787) - Windows 10.0.19041 - Single-window, 2 monitors - OpenGL 3 (Compatibility) - Intel(R) HD Graphics 620 (Intel Corporation; 26.20.100.7157) - Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 threads)`

https://github.com/user-attachments/assets/ea2ac556-1d13-4e4d-be74-b81cd0a491b8

BTW: I'm not sure, but looks like it shows embedded window correctly only when editor window is maximized.

**Comment by Hilderin** [comment]
@arkology 
I don't think the problem is the GPU, it seems it positions itself with the screen position and not the editor. I see in your video thst godot is inside some ApplicationFrameHost? What is that? 

Also, I did not test on multimonitors yet on Windows. Can you try the latest build: https://github.com/Hilderin/godot/actions/runs/11294495792

**Comment by arkology** [comment]
> I see in your video thst godot is inside some ApplicationFrameHost? What is that?

I captured screen with ShareX and looks like when it captures screen with standard Windows10 gallery app recording will be called "ApplicationFrameHost" (just tested on another PC).

> Can you try the latest build

Sure! 
Unfortunately, results are the same.
I captured screen showing "but looks like it shows embedded window correctly only when editor window is maximized" - unfortunately it's also not correct.

https://github.com/user-attachments/assets/d92d9200-f26e-4a6c-bd10-1f1724ecb2f4

**Comment by Hilderin** [comment]
Thanks for the information and debugging, I'll look into it.

**Comment by Hilderin** [comment]
I'm working on an "official" PR to the main godot repo. I'm closing this PR.

**Pull request closed without merging**
